# Generated by Django 4.2 on 2024-12-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
